# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92befc08021e3c25c427e3190216f97d72dc1d52e836c0df7f541d56dc5d9278637835ff61ad5898e3f374a7881e1a0e916e9476f8b00f25eafd040e2aad723f

test:
  secret_key_base: e4401902f88fce9469165276acff88a88d1925a1a69ad240a1c5805588273c14c0ea270858f5d5664e21aed927c4023d65de175031b3a00c61b28a90d6d700a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
